= C++ Actions
Alan Freitas <alandefreitas@gmail.com>
:description: GitHub Actions for C++ Libraries
:sectanchors:
:url-repo: https://github.com/alandefreitas/cpp-actions
:page-tags: cpp-actions
:navtitle: Home

Testing {cpp} libraries can be a challenging task, as there are various factors to consider such as the different compilers, operating systems, and architectures that the library may need to support.
Furthermore, {cpp} itself is a complex language with a wide range of features, making it difficult to write comprehensive tests that cover all possible scenarios.

To address these challenges, this repository provides a collection of GitHub actions that are specifically designed to test {cpp} libraries in a variety of environments.
These actions aim to create a common and resilient set of tools that can be used to test libraries across a wide range of platforms and configurations.

By leveraging the power of GitHub Actions, these {cpp} testing tools can be easily integrated into a development workflow, allowing developers to quickly and efficiently test their libraries with minimal effort.
This can help to ensure that the library is functioning correctly and that it is compatible with a wide range of platforms and configurations.

Whether you are a seasoned {cpp} developer or just starting out, these testing tools can help you to streamline your development workflow and ensure that your library is robust and reliable.
With a comprehensive set of testing tools at your disposal, you can focus on writing high-quality code and delivering great software to your users.


NOTE: READ THE DOCS: https://alandefreitas.github.io/cpp-actions/

== Actions
:reftext: Actions
:navtitle: All Actions

- <<setup-cpp>>
- <<package-install>>
- <<cmake-workflow>>
- <<boost-clone>>
- <<b2-workflow>>
- <<create-changelog>>
- <<setup-cmake>>
- <<setup-gcc>>
- <<setup-clang>>

=== Setup C++ [[setup-cpp]]
:reftext: Setup C++
:navtitle: Setup C++ Action
// This setup-cpp.adoc file is automatically generated.
// Edit parse_actions.py instead.

Set up a C++ compiler and add it to the PATH.

The `compiler` parameter can be used to provide a compiler name or a compiler name with its version, separated
by whitespace or a `-`. Examples valid names are `gcc`, `pass:[g++]`, `clang`, `gcc-10`, `pass:[g++ 10]`, `clang 9.2`.

Note that strings like `10` and `9.2` are semver requirements and not semver versions. For instance, `10` represents
the requirement equivalent to `>=10.0.0 <11.0.0` while `9.2` represents the requirement equivalent to 
`>=9.2.0 <9.3.0`.  

If the `compiler` parameter does not include a version requirement, the `version` parameter can be used to provide
a version semver string in the npm format with the compiler requirements.

If the compiler is GCC or Clang, this action routes to the appropriate xref:actions/setup-gcc.adoc[] or 
xref:actions/setup-clang.adoc[] actions. 

If the compiler is MSVC, this action will setup the developer command prompt for Microsoft Visual C\+\+. 

Any other compilers are passed through.

If the compiler is GCC or Clang, the outputs include the paths to the compilers as well as the compiler
version ultimately setup by the action.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: Setup C++
  uses: alandefreitas/cpp-actions/setup-cpp@master
  id: setup-cpp
  with:
    compiler: g++-10.2
----

==== Input Parameters

|===
|Parameter |Description |Default
|`compiler` |Compiler name. If the compiler contains a version, it overrides 'version'.
. |`*`
|`version` |Version range or exact version of GCC to use, using SemVer's version range syntax. 

By default, it uses any version available in the environment.
. |`*`
|`path` |The compiler executable. We attempt to find the compiler at this path first. |
|`cache` |Used to specify whether the compiler installation should be cached in case it needs to be downloaded."
. |`false`
|`architecture` |The target architecture (x86, x64). By default, this value is inferred.
. |
|`check-latest` |By default, when the compiler is not available, this action will install the minimum version in the version spec.
This ensures the code respects its contract in terms of what minimum GCC version is supported.

Set this option if you want the action to check for the latest available version that satisfies the version spec
instead.
. |`false`
|`update-environment` |Set this option if you want the action to update environment variables. |`true`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

==== Outputs

|===
|Output |Description
|`cc` |The absolute path to the C compiler executable.
|`cxx` |The absolute path to the C++ compiler executable.
|`dir` |The absolute path to the directory containing the executable.
|`version` |The installed compiler version. Useful when given a version range as input.
|`version-major` |The installed compiler version major. Useful when given a version range as input.
|`version-minor` |The installed compiler version minor. Useful when given a version range as input.
|`version-patch` |The installed compiler version patch. Useful when given a version range as input.
|`cache-hit` |A boolean value to indicate a cache entry was found
|===
=== Install Packages [[package-install]]
:reftext: Install Packages
:navtitle: Install Packages Action
// This package-install.adoc file is automatically generated.
// Edit parse_actions.py instead.

This action installs dependencies from multiple package managers for a workflow.

If vcpkg dependencies are required and vcpkg is not available, it will be installed.
Both vcpkg and its dependencies are cached.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: Install packages
  uses: alandefreitas/cpp-actions/package-install@master
  id: package-install
  with:
    vcpkg: fmt
    cxx: ${{ steps.setup-cpp.outputs.cxx || 'g++-10.2' }}
    cc: ${{ steps.setup-cpp.outputs.cc || 'gcc-10.2' }}
----

==== Input Parameters

|===
|Parameter |Description |Default
|`vcpkg` |List of packages we should install with vcpkg. (Whitespace-separated). |
|`apt-get` |List of packages we should install with apt-get. (Whitespace-separated). |
|`cxx` |C++ compiler used by vcpkg.

Setting the compiler is particularly important in Linux workflows that use `clang`, since `clang` might link 
`libc++` or `libstdc++`, while the default compiler used by vcpkg will usually be GCC linking `libstdc++`.

This would cause conflict in workflows that later attempt to use vcpkg dependencies.
. |
|`cxxflags` |C++ flags used by vcpkg.
. |
|`cc` |C compiler used by vcpkg. |
|`vcpkg-triplet` |The triplet used by vcpkg to install packages. |
|`vcpkg-dir` |The directory where vcpkg should be cloned and installed. |`vcpkg`
|`vcpkg-branch` |vcpkg branch we should use. |`master`
|`apt-get-retries` |Number of times we should retry when apt-get fails. |`1`
|`apt-get-sources` |List of sources for apt-get. |
|`apt-get-source-keys` |List of source keys for apt-get. |
|`apt-get-ignore-missing` |Whether apt-get should ignore missing packages. |`false`
|===

==== Outputs

|===
|Output |Description
|`vcpkg-toolchain` |vcpkg toolchain file
|`vcpkg-executable` |vcpkg toolchain file
|===
=== CMake Workflow [[cmake-workflow]]
:reftext: CMake Workflow
:navtitle: CMake Workflow Action
// This cmake-workflow.adoc file is automatically generated.
// Edit parse_actions.py instead.

This action runs a complete CMake workflow from source files. A workflow is composed of the following steps:

- Configure
- Build
- Test
- Install

The action also sets up the environment for the workflow: 

- It validates the CMake version installed in the system, 
- Updates CMake if the library has a different minimum version, 
- Identifies what features the current CMake version supports, and 
- Runs a complete cmake workflow

The action will adjusts the parameters as needed according to the features that CMake version supports. 
For instance, 

- If the CMake version does not support the `-S ... -B ...` syntax, the action will create the build directory and
run the configuration step from there.
- If the specified or default generator is multi-config, `CMAKE_CONFIGURATION_TYPES` will be used instead of 
`CMAKE_BUILD_TYPE`, since the later is ignored by these generators.
- If the CMake version does not support the `cmake --install` syntax, the `cmake --build --target install`
will be use instead.
- If the CMake version does not support multiple targets in the `cmake --build` syntax, the action will run the build
step once for each target.

The action also creates GitHub annotations when warnings or errors are emitted at any of these steps. This includes
annotations for CMake errors at the configure step and build errors emitted from the compiler at the build step.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: CMake Workflow
  uses: alandefreitas/cpp-actions/cmake-workflow@master
  with:
    cmake-version: '>=3.20'
    source-dir: tests
    toolchain: ${{ steps.package-install.outputs.vcpkg-toolchain }}
    run-tests: 'true'
    install-prefix: $GITHUB_WORKSPACE/.local
    cxxstd: '17'
    cc: ${{ steps.setup-cpp.outputs.cc || 'gcc-10.2' }}
    cxx: ${{ steps.setup-cpp.outputs.cxx || 'g++-10.2' }}
    extra-args: -D BOOST_SRC_DIR=$GITHUB_WORKSPACE/boost-root
    ref-source-dir: .
----

==== Input Parameters

|===
|Parameter |Description |Default
|`cmake-path` |The cmake executable. |`cmake`
|`cmake-version` |A semver range string with the cmake versions supported by this workflow. 

If the existing version in the environment does not satisfy this requirement, the action install
the min CMake version that satisfies it.

This should usually match the `cmake_minimum_required` defined in your CMakeLists.txt file.
. |
|`source-dir` |Directory for the source files. |`.`
|`build-dir` |Directory for the binaries relative to the source directory. |`build`
|`cc` |Path to C compiler. |
|`cxx` |Path to C++ compiler. |
|`cxxstd` |List of standards with which cmake will build and test the program. |
|`cxxflags` |Force flags to be used with the C++ compiler. |
|`toolchain` |Path to toolchain. |
|`generator` |Generator name. |
|`build-type` |Build type. |`Release`
|`build-target` |Targets to build instead of the default target. |
|`install-prefix` |Path where the library should be installed. |`.local/usr`
|`extra-args` |Extra arguments to cmake configure command. |
|`run-tests` |Whether we should run tests. |`true`
|`install` |Whether we should install the library. 

The library is only installed once in the `install-prefix`.

The latest std version described in `cxxstd` is used for the installed version.
. |`true`
|`create-annotations` |Create github annotations on errors. |`true`
|`ref-source-dir` |A reference source directory for annotations. Any annotation filename will be relative to this directory.

This is typically useful when the repository being tested is not the current directory, in which
we need to make annotations relative to some other directory.

In most cases, the default option should be enough.
. |`.`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

=== Boost Clone [[boost-clone]]
:reftext: Boost Clone
:navtitle: Boost Clone Action
// This boost-clone.adoc file is automatically generated.
// Edit parse_actions.py instead.

This action clones the Boost source directory, attempting to get it from the cache first. Only the specified
modules are cloned and cached.

Cloning boost is useful when one wants the always use the latest version of boost in a library or is writing
a boost proposal. For other use cases, individual boost modules can be fetched with vcpkg in 
xref:actions/package-install.adoc[] or directly included in a package manager manifest.

Besides the explicitly specified list of modules, the action can also scan directories for boost dependencies
to implicitly determine what modules should be cloned. 

The union of the implicitly and explicitly specified modules is cloned. Caching is based only on these dependencies.

For a project with about 5 boost dependencies, caching saves about 4 minutes in the workflow. When there's no
cache, the scanning scripting saves us about 3 minutes.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: Clone Boost.Variant2
  uses: alandefreitas/cpp-actions/boost-clone@master
  with:
    boost-dir: boost-root
    branch: master
    modules: variant2
----

==== Input Parameters

|===
|Parameter |Description |Default
|`boost-dir` |The boost directory. The default value assumes boost is in-source. |`boost`
|`branch` |Branch of the super-project. |`master`
|`patches` |Libraries used to patch the boost installation. |
|`modules` |The boost submodules we need to clone. |
|`modules-scan-paths` |Additional modules subdirectory to scan; can be repeated. |
|`modules-exclude-paths` |Additional modules subdirectory to scan; can be repeated. |`test`
|`scan-modules-dir` |An independent directory we should scan for boost dependencies to clone. |
|`scan-modules-ignore` |List of modules that should be ignored in scan-modules. |
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

=== B2 Workflow [[b2-workflow]]
:reftext: B2 Workflow
:navtitle: B2 Workflow Action
// This b2-workflow.adoc file is automatically generated.
// Edit parse_actions.py instead.

This action runs a complete B2 workflow from Boost source files.

It takes the Boost source directory and does whatever it needs to test the specified modules. This includes 
compiling `b2` if needed and generating a proper `user-config.jam` file.

This action is particularly useful for Boost library proposals.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2-workflow@master
  with:
    source-dir: boost-root
    modules: variant2
    toolset: gcc-10.2
    cxxstd: '17'
----

==== Input Parameters

|===
|Parameter |Description |Default
|`source-dir` |The boost source directory. |`.`
|`build-variant` |Custom build variants. |
|`modules` |The list of modules we should test. |
|`gcc-toolchain` |Create a special GCC toolchain for this version of GCC and update user-config.jam. |
|`toolset` |Toolset name. |
|`address-model` |Valid b2 list of address models. |
|`cxx` |Path to C++ compiler. |
|`cxxflags` |Extra compiler flags. |
|`linkflags` |Extra linker flags. |
|`cxxstd` |List of standards with which b2 will build and test the program. |
|`ubsan` |Whether the undefined behavior sanitizer should be used. |`false`
|`threading` |b2 threading option. |
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

=== Create Changelog [[create-changelog]]
:reftext: Create Changelog
:navtitle: Create Changelog Action
// This create-changelog.adoc file is automatically generated.
// Edit parse_actions.py instead.

This action creates an initial Changelog from the commit history.

The commits considered go from the latest commit up to a commit containing a version
commit pattern specified by version-pattern.

The result can be used as the initial body for an automated release, a CHANGELOG.md file, or a job summary.

Each commit is parsed as a loose variant of a https://www.conventionalcommits.org/en/v1.0.0/[conventional commit]
in the following format:

[source,none]
----
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
----

* The body and footer are always ignored.
* If no type is indicated, the description goes to an initial "other" category in the message.
* If no scope is indicated, the description goes to an initial "general" scope in the type messages.
* Breaking changes are indicated.

This action uses the local commit history to generate the notes. Ensure the `fetch-depth` option
is set when cloning your repository in CI. If this option is unset, the checkout action will
perform a shallow clone and the Changelog will only include the latest commit.

[source,yml]
----
- uses: actions/checkout@v3
  with:
    fetch-depth: 100
----

This parameter can also be used as a limit on the number of commits the action should consider.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: Create release notes
  uses: alandefreitas/cpp-actions/create-changelog@master
  with:
    output-path: CHANGELOG.md
----

==== Input Parameters

|===
|Parameter |Description |Default
|`source-dir` |The source directory from whose commits will be analyzed
. |`.`
|`version-pattern` |A regex pattern used to identify if a commit is a version delimiter.

When a commit has a message that matches this pattern, the list of
commits considered in the notes is complete.

This constraint does not apply to the current and latest commit.
. |`(Bump\|Set)\s+version`
|`tag-pattern` |A regex pattern used to identify if a commit is a tagged delimiter.

When a commit has the same hash has the commit associated with a
tag whose name matches this pattern, the list of commits considered
in the notes is complete.

This constraint does not apply to the current and latest commit.
. |`v.*\..*\..*`
|`output-path` |The path where the changelog will be stored
. |`CHANGELOG.md`
|`limit` |The limit on the number of commits considered in the Changelog
. |`0`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

=== Setup CMake [[setup-cmake]]
:reftext: Setup CMake
:navtitle: Setup CMake Action
// This setup-cmake.adoc file is automatically generated.
// Edit parse_actions.py instead.

Set up a specific version of a CMake compiler and add it to the PATH.

This action will also set-up any dependencies required by CMake.

In most workflows, this is used as an auxiliary action for the xref:actions/cmake-workflow.adoc[] action. 


==== Input Parameters

|===
|Parameter |Description |Default
|`version` |Version range or exact version of CMake to use, using SemVer's version range syntax. 

Reads from `cmake-file` input if unset.

By default, it uses any version available in the environment.
. |`*`
|`cmake-file` |File containing the CMake version to use in a cmake_minimum_required command. 

Example: A CMakeLists.txt file containing a call to cmake_minimum_required."
. |`CMakeLists.txt`
|`cmake-path` |The cmake executable. We attempt to find cmake at this path first. |`cmake`
|`cache` |Used to specify whether the CMake installation should be cached in the case CMake needs to be downloaded."
. |`True`
|`architecture` |The target architecture (x86, x64). By default, this value is inferred.
. |
|`check-latest` |By default, when CMake is not available, this action will install the minimum version in the version spec.
This ensures the code respects its contract in terms of what minimum CMake version is supported.

Set this option if you want the action to check for the latest available version that satisfies the version spec
instead.
. |
|`update-environment` |Set this option if you want the action to update environment variables. |`True`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

==== Outputs

|===
|Output |Description
|`version` |The installed CMake version. Useful when given a version range as input.
|`version-major` |The installed CMake version major. Useful when given a version range as input.
|`version-minor` |The installed CMake version minor. Useful when given a version range as input.
|`version-patch` |The installed CMake version patch. Useful when given a version range as input.
|`cache-hit` |A boolean value to indicate a cache entry was found
|`path` |The absolute path to the CMake executable.
|`dir` |The absolute path to the CMake directory.
|`supports-path-to-build` |Whether CMake supports the -B <path-to-build> syntax
|`supports-parallel-build` |Whether CMake supports the -j <threads> syntax
|`supports-build-multiple-targets` |Whether CMake supports the --target with multiple targets
|`supports-cmake-install` |Whether CMake supports the cmake --install
|===
=== Setup GCC [[setup-gcc]]
:reftext: Setup GCC
:navtitle: Setup GCC Action
// This setup-gcc.adoc file is automatically generated.
// Edit parse_actions.py instead.

Set up a specific version of a GCC compiler and add it to the PATH.
In most workflows, this is used as an auxiliary action for the setup-cpp action.

This allows us to test a C++ library with any GCC version, and not only the versions 
circumstantially provided by apt-get.

This action uses a number of alternatives to find or install GCC:

- The GCC path provided to 'path'
- Any other version of GCC it can find in the system
- Any other version of GCC available from APT
- A version of GCC from our own binary releases

The action will *not* attempt to install GCC from source files, which is the only 
officially supported method but impossible to run in CI because the machines would take
hours to do that.

If a version of GCC is not available by any other methods above, the GCC binaries for
a given platform can be built locally with a 
https://github.com/alandefreitas/cpp-actions/tree/develop/setup-gcc[script,window="_blank"]
provided in this repository and added to our binary release. 


==== Input Parameters

|===
|Parameter |Description |Default
|`version` |Version range or exact version of GCC to use, using SemVer's version range syntax. 

By default, it uses any version available in the environment.
. |`*`
|`path` |The gcc or g++ executable. We attempt to find GCC at this path first. |`g++`
|`cache` |Used to specify whether the GCC installation should be cached in the case GCC needs to be downloaded."
. |`false`
|`architecture` |The target architecture (x86, x64). By default, this value is inferred.
. |
|`check-latest` |By default, when GCC is not available, this action will install the minimum version in the version spec.
This ensures the code respects its contract in terms of what minimum GCC version is supported.

Set this option if you want the action to check for the latest available version that satisfies the version spec
instead.
. |`false`
|`update-environment` |Set this option if you want the action to update environment variables. |`true`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

==== Outputs

|===
|Output |Description
|`cc` |The absolute path to the gcc executable.
|`cxx` |The absolute path to the g++ executable.
|`dir` |The absolute path to the GCC directory containing the executable.
|`version` |The installed GCC version. Useful when given a version range as input.
|`version-major` |The installed GCC version major. Useful when given a version range as input.
|`version-minor` |The installed GCC version minor. Useful when given a version range as input.
|`version-patch` |The installed GCC version patch. Useful when given a version range as input.
|`cache-hit` |A boolean value to indicate a cache entry was found
|===
=== Setup Clang [[setup-clang]]
:reftext: Setup Clang
:navtitle: Setup Clang Action
// This setup-clang.adoc file is automatically generated.
// Edit parse_actions.py instead.

Set up a specific version of a Clang compiler and add it to the PATH.
In most workflows, this is used as an auxiliary action for the setup-cpp action.

This allows us to test a C++ library with any Clang version, and not only the versions 
circumstantially provided by apt-get.

This action uses a number of alternatives to find or install Clang:

- The Clang path provided to 'path'
- Any other version of Clang it can find in the system
- Any other version of Clang available from APT
- A version of Clang from our own binary releases


==== Input Parameters

|===
|Parameter |Description |Default
|`version` |Version range or exact version of Clang to use, using SemVer's version range syntax. 

By default, it uses any version available in the environment.
. |`*`
|`path` |The clang or clang++ executable. We attempt to find Clang at this path first. |`clang++`
|`cache` |Used to specify whether the Clang installation should be cached in the case Clang needs to be downloaded."
. |`false`
|`architecture` |The target architecture (x86, x64). By default, this value is inferred.
. |
|`check-latest` |By default, when Clang is not available, this action will install the minimum version in the version spec.
This ensures the code respects its contract in terms of what minimum Clang version is supported.

Set this option if you want the action to check for the latest available version that satisfies the version spec
instead.
. |`false`
|`update-environment` |Set this option if you want the action to update environment variables. |`true`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

==== Outputs

|===
|Output |Description
|`cc` |The absolute path to the clang executable.
|`cxx` |The absolute path to the clang++ executable.
|`dir` |The absolute path to the Clang directory containing the executable.
|`version` |The installed Clang version. Useful when given a version range as input.
|`version-major` |The installed Clang version major. Useful when given a version range as input.
|`version-minor` |The installed Clang version minor. Useful when given a version range as input.
|`version-patch` |The installed Clang version patch. Useful when given a version range as input.
|`cache-hit` |A boolean value to indicate a cache entry was found
|===


== Contributions

If there's a platform where one of the actions does not work, feel free to submit a PR with adaptations and tests.

== License

[]
====
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
====

