= C++ Actions
Alan Freitas <alandefreitas@gmail.com>
:description: GitHub Actions for C++ Libraries
:sectanchors:
:url-repo: https://github.com/alandefreitas/cpp-actions
:page-tags: cpp-actions
:navtitle: Home

Testing {cpp} libraries can be a challenging task, as there are various factors to consider such as the different compilers, operating systems, and architectures that the library may need to support.
Furthermore, {cpp} itself is a complex language with a wide range of features, making it difficult to write comprehensive tests that cover all possible scenarios.

To address these challenges, this repository provides a collection of GitHub actions that are specifically designed to test {cpp} libraries in a variety of environments.
These actions aim to create a common and resilient set of tools that can be used to test libraries across a wide range of platforms and configurations.

By leveraging the power of GitHub Actions, these {cpp} testing tools can be easily integrated into a development workflow, allowing developers to quickly and efficiently test their libraries with minimal effort.
This can help to ensure that the library is functioning correctly and that it is compatible with a wide range of platforms and configurations.

Whether you are a seasoned {cpp} developer or just starting out, these testing tools can help you to streamline your development workflow and ensure that your library is robust and reliable.
With a comprehensive set of testing tools at your disposal, you can focus on writing high-quality code and delivering great software to your users.


NOTE: READ THE DOCS: https://alandefreitas.github.io/cpp-actions/

== Actions
:reftext: Actions
:navtitle: All Actions

- <<cpp-matrix>>
- <<setup-cpp>>
- <<package-install>>
- <<cmake-workflow>>
- <<boost-clone>>
- <<b2-workflow>>
- <<create-changelog>>
- <<setup-cmake>>
- <<setup-gcc>>
- <<setup-clang>>

=== C++ Matrix [[cpp-matrix]]
:reftext: C++ Matrix
:navtitle: C++ Matrix Action
// This cpp-matrix.adoc file is automatically generated.
// Edit parse_actions.py instead.

Testing C++ libraries can be a challenging and time-consuming task, especially when considering the
various compiler versions, error behaviors, and platform dependencies. A library that works flawlessly 
with one compiler might encounter issues when compiled with a different version or on a different
platform. This is where the C++ Library Test Matrix GitHub Action comes to the rescue.

The C++ Library Test Matrix GitHub Action is designed to automate the generation of a comprehensive 
test matrix for your C++ libraries given their requirements. It simplifies the process of testing your
libraries across multiple compiler versions and platforms, reducing the manual effort and potential 
for human error.

With this action, you can define a set of compiler versions, target platforms, standard requirements,
and factors that you want to test your C++ library against. The action then automatically generates 
a test matrix by combining the specified compilers and platforms into a fractional factorial design, 
enabling you to run tests in a systematic and efficient manner.

This action can ensure that your C++ library is thoroughly tested across a wide range of compiler
versions and platforms. This approach significantly increases the chances of catching compatibility 
issues early on and helps in delivering a robust and reliable library that works across different
environments.

- Automated test matrix generation: Define a list of compiler versions and platforms, and let the action handle 
  the creation of the test matrix.
- Easy integration: Simply include the C++ Library Test Matrix GitHub Action in your workflow configuration to 
  start generating the test matrix.
- Customization options: Fine-tune the test matrix generation process by specifying additional compiler flags, 
  build configurations, or test suites.
- Comprehensive test coverage: Ensure your C++ library is thoroughly tested across multiple compiler versions 
  and platforms to identify and address compatibility issues.

Get started with the C++ Library Test Matrix GitHub Action today and streamline your C++ library testing 
process. Say goodbye to manual matrix creation and embrace automated, systematic testing to deliver 
high-quality C++ libraries that work seamlessly across different compilers and platforms.

==== Usage

The action should be run as extra initial "`setup`" job in your workflow. The job will run the action and 
output `matrix`, which is a JSON string containing the whole matrix. This matrix should be output of your 
first `setup` job.

In your second `build` job, you can attribute the entire matrix to the `strategy.matrix.include` parameter
and create your workflow as usual with the parameters from the matrix:

[source,yml,subs="attributes+"]
----
jobs:
  cpp-matrix:
    runs-on: ubuntu-latest
    name: Generate Test Matrix
    outputs:
      matrix: ${{ steps.cpp-matrix.outputs.matrix }}
    steps:
      - name: Generate Test Matrix
        uses: alandefreitas/cpp-actions/cpp-matrix@master
        id: cpp-matrix
        with:
          standards: '>=11'
  build:
    needs: cpp-matrix
    strategy:
      fail-fast: false
      matrix:
        include: fromJSON(needs.cpp-matrix.outputs.matrix)

    # use matrix entries 
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}

    steps:
      - name: Clone library
        uses: actions/checkout@v3

      - name: Setup C++ Compiler
        uses: alandefreitas/cpp-actions/setup-cpp@master
        id: setup-cpp
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      - name: CMake Workflow
        uses: ./cmake-workflow
        with:
          cc: ${{ steps.setup-cpp.outputs.cc || matrix.cc }}
          cxx: ${{ steps.setup-cpp.outputs.cxx || matrix.cxx }}
          cxxstd: ${{ matrix.cxxstd }}
          cxxflags: ${{ matrix.cxxstd }}

      # And you've safely tested your C++ library just like that...
----


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: Generate Test Matrix
  uses: alandefreitas/cpp-actions/cpp-matrix@master
  id: cpp-matrix
  with:
    standards: '>=11'
----

==== Input Parameters

|===
|Parameter |Description |Default
|`compilers` |A list of compilers to be tested. Each compiler can be complemented with its semver version requirements
to be tested. 

When the compiler version requirements are provided, the action will break the requirements into 
subsets of major versions to be tested. When no version is provided, the '*' semver requirement
is assumed. The action can identifies subsets of compiler versions for GCC, Clang, and MSVC.
For any other compilers, the version requirements will passthrough to the output.
. |`gcc >=4.8`

`clang >=3.8`

`msvc >=14.2`

`apple-clang *`
|`standards` |A semver range describing what C++ standards should be tested.

The compiler ranges are adjusted to only include compilers that support any subrange of these requirements.

These requirements can include C++ standards as 2 or 4 digits versions, such as 11, 2011, 98, or 1998.
2 digit versions are normalized into the 4 digits form so that 11 > 98 (2011 > 1998).
. |`>=11`
|`max-standards` |The maximum number of standards to be tested with each compiler.

For instance, if 'max-standards' is 2 and the compiler supports '11,14,17,20,23' given the in the standard
requirements, the standards 20,23 will be tested by this compiler. 
. |`2`
|`latest-factors` |The factors to be tested with the latest versions of each compiler. For each factor in this list, the
entry with the latest version of a compiler will be duplicated with an entry that sets this factor to true.

Other entries will also include this factor as false.

The following factors are considered special: 'asan', 'ubsan', 'msan', 'tsan', and 'coverage'.
When these factors are defined in an entry, its 'ccflags', 'cxxflags', and 'linkflags' value are
also modified to include the suggested flags for factor.
. |`gcc Coverage TSan UBSan`
|`factors` |The factors to be tested with other versions of each compiler. Each factor in this list will be injected
into a version of the compiler that is not the latest version. An entry with the latest version of the compiler
will be duplicated with this factor if there are no entries left to inject the factor.

Other entries will also include this factor as false.
. |`gcc Asan Shared`

`msvc Shared x86`

`clang Time-Trace`
|`trace-commands` |Trace commands executed by the action. |`false`
|===

==== Outputs

|===
|Output |Description
|`matrix` |The test matrix is an array of dictionaries, where each entry represents a combination of compiler version
and factors to be tested. 

Each entry in the test matrix dictionary contains the following key-value pairs:

- `name`: A suggested name for the job testing this entry

- `runs-on`: A suggested github runner image name for the job testing this entry

- `container`: A suggested docker container for the job testing this entry

- `compiler`: Specifies the name of the compiler to be used for the test configuration. This can be used as
  input to the setup-cpp action.

- `version`: Specifies the version requirements of the compiler to be used for the test configuration. This can
  be used as input to the setup-cpp action.

- `is-latest`: Specifies whether this version requirement is the latest version among the test configurations.

- `is-earliest`: Specifies whether this version requirement is the earliest version among the test configurations.

- `cxx`: The usual name of the C++ compiler executable. If using the `setup-cpp` action, its output should be used 
  instead. 

- `cc`: The usual name of the C compiler executable. If using the `setup-cpp` action, its output should be used 
  instead. 

- `cxxstd`: A list of standards that should be tested with this compiler version. This option considers
  the `max-standards` latest standards supported by each compiler in its subrange of `standards`.

- `b2-toolset`: The usual name of the toolset to be used in a b2 workflow.

- `generator`: A CMake generator recommended to run the CMake workflow.

- `build-type`: A build type recommended to test this entry. This is usually `Release`, unless some special 
  factor that requires `Debug` is defined.

- `ccflags`: The recommended C flags to be used by this entry. It reflects the values of special factors, such
   as sanitizers, coverage, and time-trace.

- `cxxflags`: The recommended C++ flags to be used by this entry. It reflects the values of special factors, such
   as sanitizers, coverage, and time-trace.

- `<factors>...`: Provides additional factors or attributes associated with the test configuration as defined by
  the factors and latest-factors inputs. These usually include variant build configurations spread among the
  entries, such as asan, coverage, and shared libraries.

|===
=== Setup C++ [[setup-cpp]]
:reftext: Setup C++
:navtitle: Setup C++ Action
// This setup-cpp.adoc file is automatically generated.
// Edit parse_actions.py instead.

Set up a C++ compiler and add it to the PATH.

The `compiler` parameter can be used to provide a compiler name or a compiler name with its version, separated
by whitespace or a `-`. Examples valid names are `gcc`, `pass:[g++]`, `clang`, `gcc-10`, `pass:[g++ 10]`, `clang 9.2`.

Note that strings like `10` and `9.2` are semver requirements and not semver versions. For instance, `10` represents
the requirement equivalent to `>=10.0.0 <11.0.0` while `9.2` represents the requirement equivalent to 
`>=9.2.0 <9.3.0`.  

If the `compiler` parameter does not include a version requirement, the `version` parameter can be used to provide
a version semver string in the npm format with the compiler requirements.

If the compiler is GCC or Clang, this action routes to the appropriate xref:actions/setup-gcc.adoc[] or 
xref:actions/setup-clang.adoc[] actions. 

If the compiler is MSVC, this action will setup the developer command prompt for Microsoft Visual C\+\+. 

Any other compilers are passed through.

If the compiler is GCC or Clang, the outputs include the paths to the compilers as well as the compiler
version ultimately setup by the action.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: Setup C++
  uses: alandefreitas/cpp-actions/setup-cpp@master
  id: setup-cpp
  with:
    compiler: ${{ matrix.compiler }}
    version: ${{ matrix.version }}
----

==== Input Parameters

|===
|Parameter |Description |Default
|`compiler` |Compiler name. If the compiler contains a version, it overrides 'version'.
. |`*`
|`version` |Version range or exact version of GCC to use, using SemVer's version range syntax. 

By default, it uses any version available in the environment.
. |`*`
|`path` |The compiler executable. We attempt to find the compiler at this path first. |
|`cache` |Used to specify whether the compiler installation should be cached in case it needs to be downloaded."
. |`false`
|`architecture` |The target architecture (x86, x64). By default, this value is inferred.
. |
|`check-latest` |By default, when the compiler is not available, this action will install the minimum version in the version spec.
This ensures the code respects its contract in terms of what minimum GCC version is supported.

Set this option if you want the action to check for the latest available version that satisfies the version spec
instead.
. |`false`
|`update-environment` |Set this option if you want the action to update environment variables. |`true`
|`update-ld-library-path` |Set this option if you want the action to update LD_LIBRARY_PATH.

Updating LD_LIBRARY_PATH might cause conflicts with system libraries and
is usually unnecessary because the binaries are built on equivalent 
containers. 

However, this is necessary on some custom containers and you can set
this option to let the action automatically add GCC library paths to 
LD_LIBRARY_PATH.
. |`false`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

==== Outputs

|===
|Output |Description
|`cc` |The absolute path to the C compiler executable.
|`cxx` |The absolute path to the C++ compiler executable.
|`dir` |The absolute path to the directory containing the executable.
|`version` |The installed compiler version. Useful when given a version range as input.
|`version-major` |The installed compiler version major. Useful when given a version range as input.
|`version-minor` |The installed compiler version minor. Useful when given a version range as input.
|`version-patch` |The installed compiler version patch. Useful when given a version range as input.
|`cache-hit` |A boolean value to indicate a cache entry was found
|===
=== Install Packages [[package-install]]
:reftext: Install Packages
:navtitle: Install Packages Action
// This package-install.adoc file is automatically generated.
// Edit parse_actions.py instead.

This action installs dependencies from multiple package managers for a workflow.

If vcpkg dependencies are required and vcpkg is not available, it will be installed.
Both vcpkg and its dependencies are cached.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: Install packages
  uses: alandefreitas/cpp-actions/package-install@master
  id: package-install
  with:
    vcpkg: fmt
    apt-get: ${{ join(matrix.install, ' ') }} ${{ matrix.container && 'sudo software-properties-common
      wget curl apt-transport-https make apt-file unzip libssl-dev build-essential
      autotools-dev autoconf automake g++ libc++-helpers python ruby cpio gcc-multilib
      g++-multilib pkgconf python3 ccache libpython-dev python3-distutils python3-pip
      git cmake' }}
    apt-get-ignore-missing: ${{ matrix.container && 'true' }}
    cc: ${{ steps.setup-cpp.outputs.cc || matrix.cc }}
    ccflags: ${{ matrix.ccflags }}
    cxx: ${{ steps.setup-cpp.outputs.cxx || matrix.cxx }}
    cxxflags: ${{ matrix.cxxflags }}
----

==== Input Parameters

|===
|Parameter |Description |Default
|`vcpkg` |List of packages we should install with vcpkg. (Whitespace-separated). |
|`apt-get` |List of packages we should install with apt-get. (Whitespace-separated). |
|`cxx` |C++ compiler used by vcpkg.

Setting the compiler is particularly important in Linux workflows that use `clang`, since `clang` might link 
`libc++` or `libstdc++`, while the default compiler used by vcpkg will usually be GCC linking `libstdc++`.

This would cause conflict in workflows that later attempt to use vcpkg dependencies.
. |
|`cxxflags` |C++ flags used by vcpkg.
. |
|`cc` |C compiler used by vcpkg. |
|`ccflags` |C flags used by vcpkg.
. |
|`vcpkg-triplet` |The triplet used by vcpkg to install packages. |
|`vcpkg-dir` |The directory where vcpkg should be cloned and installed. |`vcpkg`
|`vcpkg-branch` |vcpkg branch we should use. |`master`
|`apt-get-retries` |Number of times we should retry when apt-get fails. |`1`
|`apt-get-sources` |List of sources for apt-get. |
|`apt-get-source-keys` |List of source keys for apt-get. |
|`apt-get-ignore-missing` |Whether apt-get should ignore missing packages. |`false`
|`trace-commands` |Trace commands executed by the action. |`false`
|===

==== Outputs

|===
|Output |Description
|`vcpkg-toolchain` |vcpkg toolchain file
|`vcpkg-executable` |vcpkg toolchain file
|===
=== CMake Workflow [[cmake-workflow]]
:reftext: CMake Workflow
:navtitle: CMake Workflow Action
// This cmake-workflow.adoc file is automatically generated.
// Edit parse_actions.py instead.

This action runs a complete CMake workflow from source files. A workflow is composed of the following steps:

- Configure
- Build
- Test
- Install

The action also sets up the environment for the workflow: 

- It validates the CMake version installed in the system, 
- Updates CMake if the library has a different minimum version, 
- Identifies what features the current CMake version supports, and 
- Runs a complete cmake workflow

The action will adjusts the parameters as needed according to the features that CMake version supports. 
For instance, 

- If the CMake version does not support the `-S ... -B ...` syntax, the action will create the build directory and
run the configuration step from there.
- If the specified or default generator is multi-config, `CMAKE_CONFIGURATION_TYPES` will be used instead of 
`CMAKE_BUILD_TYPE`, since the later is ignored by these generators.
- If the CMake version does not support the `cmake --install` syntax, the `cmake --build --target install`
will be use instead.
- If the CMake version does not support multiple targets in the `cmake --build` syntax, the action will run the build
step once for each target.

The action also creates GitHub annotations when warnings or errors are emitted at any of these steps. This includes
annotations for CMake errors at the configure step and build errors emitted from the compiler at the build step.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: CMake Workflow
  uses: alandefreitas/cpp-actions/cmake-workflow@master
  with:
    cmake-version: '>=3.20'
    source-dir: tests
    generator: ${{ matrix.generator }}
    toolchain: ${{ steps.package-install.outputs.vcpkg-toolchain }}
    build-type: ${{ matrix.build-type }}
    run-tests: true
    install-prefix: $GITHUB_WORKSPACE/.local
    cxxstd: ${{ matrix.cxxstd }}
    cc: ${{ steps.setup-cpp.outputs.cc || matrix.cc }}
    ccflags: ${{ matrix.ccflags }}
    cxx: ${{ steps.setup-cpp.outputs.cxx || matrix.cxx }}
    cxxflags: ${{ matrix.cxxflags }}
    extra-args: -D BOOST_SRC_DIR="${{ steps.boost-clone.outputs.boost-dir }}"
    ref-source-dir: .
----

==== Input Parameters

|===
|Parameter |Description |Default
|`cmake-path` |The cmake executable. |`cmake`
|`cmake-version` |A semver range string with the cmake versions supported by this workflow. 

If the existing version in the environment does not satisfy this requirement, the action install
the min CMake version that satisfies it.

This should usually match the `cmake_minimum_required` defined in your CMakeLists.txt file.
. |
|`source-dir` |Directory for the source files. |`.`
|`build-dir` |Directory for the binaries relative to the source directory. |`build`
|`cc` |Path to C compiler. |
|`ccflags` |Flags to be used with the C compiler. |
|`cxx` |Path to C++ compiler. |
|`cxxstd` |List of standards with which cmake will build and test the program. |
|`cxxflags` |Flags to be used with the C++ compiler. |
|`toolchain` |Path to toolchain. |
|`generator` |Generator name. |
|`build-type` |Build type. |`Release`
|`build-target` |Targets to build instead of the default target. |
|`install-prefix` |Path where the library should be installed. |`.local/usr`
|`extra-args` |Extra arguments to cmake configure command. |
|`run-tests` |Whether we should run tests. |`true`
|`install` |Whether we should install the library. 

The library is only installed once in the `install-prefix`.

The latest std version described in `cxxstd` is used for the installed version.
. |`true`
|`create-annotations` |Create github annotations on errors. |`true`
|`ref-source-dir` |A reference source directory for annotations. Any annotation filename will be relative to this directory.

This is typically useful when the repository being tested is not the current directory, in which
we need to make annotations relative to some other directory.

In most cases, the default option should be enough.
. |`.`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

=== Boost Clone [[boost-clone]]
:reftext: Boost Clone
:navtitle: Boost Clone Action
// This boost-clone.adoc file is automatically generated.
// Edit parse_actions.py instead.

This action clones the Boost source directory, attempting to get it from the cache first. Only the specified
modules are cloned and cached.

Cloning boost is useful when one wants the always use the latest version of boost in a library or is writing
a boost proposal. For other use cases, individual boost modules can be fetched with vcpkg in 
xref:actions/package-install.adoc[] or directly included in a package manager manifest.

Besides the explicitly specified list of modules, the action can also scan directories for boost dependencies
to implicitly determine what modules should be cloned. 

The union of the implicitly and explicitly specified modules is cloned. Caching is based only on these dependencies.

For a project with about 5 boost dependencies, caching saves about 4 minutes in the workflow. When there's no
cache, the scanning scripting saves us about 3 minutes.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: Clone Boost.Variant2
  uses: alandefreitas/cpp-actions/boost-clone@master
  id: boost-clone
  with:
    branch: master
    modules: variant2
----

==== Input Parameters

|===
|Parameter |Description |Default
|`boost-dir` |The boost directory. The default value assumes boost is in-source. |
|`branch` |Branch of the super-project. |`master`
|`patches` |Libraries used to patch the boost installation. |
|`modules` |The boost submodules we need to clone. |
|`modules-scan-paths` |Additional modules subdirectory to scan; can be repeated. |
|`modules-exclude-paths` |Additional modules subdirectory to scan; can be repeated. |`test`
|`scan-modules-dir` |An independent directory we should scan for boost dependencies to clone. |
|`scan-modules-ignore` |List of modules that should be ignored in scan-modules. |
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

==== Outputs

|===
|Output |Description
|`boost-dir` |The absolute path to the boost source files.
|===
=== B2 Workflow [[b2-workflow]]
:reftext: B2 Workflow
:navtitle: B2 Workflow Action
// This b2-workflow.adoc file is automatically generated.
// Edit parse_actions.py instead.

This action runs a complete B2 workflow from Boost source files.

It takes the Boost source directory and does whatever it needs to test the specified modules. This includes 
compiling `b2` if needed and generating a proper `user-config.jam` file.

This action is particularly useful for Boost library proposals.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2-workflow@master
  with:
    source-dir: ${{ steps.boost-clone.outputs.boost-dir }}
    modules: variant2
    toolset: ${{ matrix.b2-toolset }}
    cxxstd: ${{ matrix.cxxstd }}
    cxx: ${{ (startsWith(matrix.cxx, 'clang') && (steps.setup-cpp.outputs.cxx || matrix.cxx))
      || '' }}
    address-model: ${{ (matrix.x86 && '32') || '64' }}
    ubsan: ${{ matrix.ubsan }}
----

==== Input Parameters

|===
|Parameter |Description |Default
|`source-dir` |The boost source directory. |`.`
|`build-variant` |Custom build variants. |
|`modules` |The list of modules we should test. |
|`gcc-toolchain` |Create a special GCC toolchain for this version of GCC and update user-config.jam. |
|`toolset` |Toolset name. |
|`address-model` |Valid b2 list of address models. |
|`cxx` |Path to C++ compiler. |
|`cxxflags` |Extra compiler flags. |
|`linkflags` |Extra linker flags. |
|`cxxstd` |List of standards with which b2 will build and test the program. |
|`ubsan` |Whether the undefined behavior sanitizer should be used. |`false`
|`threading` |b2 threading option. |
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

=== Create Changelog [[create-changelog]]
:reftext: Create Changelog
:navtitle: Create Changelog Action
// This create-changelog.adoc file is automatically generated.
// Edit parse_actions.py instead.

This action creates an initial Changelog from the commit history.

The commits considered go from the latest commit up to a commit containing a version
commit pattern specified by version-pattern.

The result can be used as the initial body for an automated release, a CHANGELOG.md file, or a job summary.

Each commit is parsed as a loose variant of a https://www.conventionalcommits.org/en/v1.0.0/[conventional commit]
in the following format:

[source,none]
----
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
----

* The body and footer are always ignored.
* If no type is indicated, the description goes to an initial "other" category in the message.
* If no scope is indicated, the description goes to an initial "general" scope in the type messages.
* Breaking changes are indicated.

This action uses the local commit history to generate the notes. Ensure the `fetch-depth` option
is set when cloning your repository in CI. If this option is unset, the checkout action will
perform a shallow clone and the Changelog will only include the latest commit.

[source,yml]
----
- uses: actions/checkout@v3
  with:
    fetch-depth: 100
----

This parameter can also be used as a limit on the number of commits the action should consider.


==== Example

[source,yml,subs="attributes+"]
----
steps:
- name: Create release notes
  uses: alandefreitas/cpp-actions/create-changelog@master
  with:
    output-path: CHANGELOG.md
----

==== Input Parameters

|===
|Parameter |Description |Default
|`source-dir` |The source directory from whose commits will be analyzed
. |`.`
|`version-pattern` |A regex pattern used to identify if a commit is a version delimiter.

When a commit has a message that matches this pattern, the list of
commits considered in the notes is complete.

This constraint does not apply to the current and latest commit.
. |`(Bump\|Set)\s+version`
|`tag-pattern` |A regex pattern used to identify if a commit is a tagged delimiter.

When a commit has the same hash has the commit associated with a
tag whose name matches this pattern, the list of commits considered
in the notes is complete.

This constraint does not apply to the current and latest commit.
. |`v.*\..*\..*`
|`output-path` |The path where the changelog will be stored
. |`CHANGELOG.md`
|`limit` |The limit on the number of commits considered in the Changelog
. |`0`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

=== Setup CMake [[setup-cmake]]
:reftext: Setup CMake
:navtitle: Setup CMake Action
// This setup-cmake.adoc file is automatically generated.
// Edit parse_actions.py instead.

Set up a specific version of a CMake compiler and add it to the PATH.

This action will also set-up any dependencies required by CMake.

In most workflows, this is used as an auxiliary action for the xref:actions/cmake-workflow.adoc[] action. 


==== Input Parameters

|===
|Parameter |Description |Default
|`version` |Version range or exact version of CMake to use, using SemVer's version range syntax. 

Reads from `cmake-file` input if unset.

By default, it uses any version available in the environment.
. |`*`
|`cmake-file` |File containing the CMake version to use in a cmake_minimum_required command. 

Example: A CMakeLists.txt file containing a call to cmake_minimum_required."
. |`CMakeLists.txt`
|`cmake-path` |The cmake executable. We attempt to find cmake at this path first. |`cmake`
|`cache` |Used to specify whether the CMake installation should be cached in the case CMake needs to be downloaded."
. |`True`
|`architecture` |The target architecture (x86, x64). By default, this value is inferred.
. |
|`check-latest` |By default, when CMake is not available, this action will install the minimum version in the version spec.
This ensures the code respects its contract in terms of what minimum CMake version is supported.

Set this option if you want the action to check for the latest available version that satisfies the version spec
instead.
. |
|`update-environment` |Set this option if you want the action to update environment variables. |`True`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

==== Outputs

|===
|Output |Description
|`version` |The installed CMake version. Useful when given a version range as input.
|`version-major` |The installed CMake version major. Useful when given a version range as input.
|`version-minor` |The installed CMake version minor. Useful when given a version range as input.
|`version-patch` |The installed CMake version patch. Useful when given a version range as input.
|`cache-hit` |A boolean value to indicate a cache entry was found
|`path` |The absolute path to the CMake executable.
|`dir` |The absolute path to the CMake directory.
|`supports-path-to-build` |Whether CMake supports the -B <path-to-build> syntax
|`supports-parallel-build` |Whether CMake supports the -j <threads> syntax
|`supports-build-multiple-targets` |Whether CMake supports the --target with multiple targets
|`supports-cmake-install` |Whether CMake supports the cmake --install
|===
=== Setup GCC [[setup-gcc]]
:reftext: Setup GCC
:navtitle: Setup GCC Action
// This setup-gcc.adoc file is automatically generated.
// Edit parse_actions.py instead.

Set up a specific version of a GCC compiler and add it to the PATH.
In most workflows, this is used as an auxiliary action for the setup-cpp action.

This allows us to test a C++ library with any GCC version, and not only the versions 
circumstantially provided by apt-get.

This action uses a number of alternatives to find or install GCC:

- The GCC path provided to 'path'
- Any other version of GCC it can find in the system
- Any other version of GCC available from APT
- A version of GCC from our own binary releases

The action will *not* attempt to install GCC from source files, which is the only 
officially supported method but impossible to run in CI because the machines would take
hours to do that.

If a version of GCC is not available by any other methods above, the GCC binaries for
a given platform can be built locally with a 
https://github.com/alandefreitas/cpp-actions/tree/develop/setup-gcc[script,window="_blank"]
provided in this repository and added to our binary release. 


==== Input Parameters

|===
|Parameter |Description |Default
|`version` |Version range or exact version of GCC to use, using SemVer's version range syntax. 

By default, it uses any version available in the environment.
. |`*`
|`path` |The gcc or g++ executable. We attempt to find GCC at this path first. |`g++`
|`cache` |Used to specify whether the GCC installation should be cached in the case GCC needs to be downloaded."
. |`false`
|`architecture` |The target architecture (x86, x64). By default, this value is inferred.
. |
|`check-latest` |By default, when GCC is not available, this action will install the minimum version in the version spec.
This ensures the code respects its contract in terms of what minimum GCC version is supported.

Set this option if you want the action to check for the latest available version that satisfies the version spec
instead.
. |`false`
|`update-environment` |Set this option if you want the action to update environment variables. |`true`
|`update-ld-library-path` |Set this option if you want the action to update LD_LIBRARY_PATH.

Updating LD_LIBRARY_PATH might cause conflicts with system libraries and
is usually unnecessary because the binaries are built on equivalent 
containers. 

However, this is necessary on some custom containers and you can set
this option to let the action automatically add GCC library paths to 
LD_LIBRARY_PATH.
. |`false`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

==== Outputs

|===
|Output |Description
|`cc` |The absolute path to the gcc executable.
|`cxx` |The absolute path to the g++ executable.
|`dir` |The absolute path to the GCC directory containing the executable.
|`version` |The installed GCC version. Useful when given a version range as input.
|`version-major` |The installed GCC version major. Useful when given a version range as input.
|`version-minor` |The installed GCC version minor. Useful when given a version range as input.
|`version-patch` |The installed GCC version patch. Useful when given a version range as input.
|`cache-hit` |A boolean value to indicate a cache entry was found
|===
=== Setup Clang [[setup-clang]]
:reftext: Setup Clang
:navtitle: Setup Clang Action
// This setup-clang.adoc file is automatically generated.
// Edit parse_actions.py instead.

Set up a specific version of a Clang compiler and add it to the PATH.
In most workflows, this is used as an auxiliary action for the setup-cpp action.

This allows us to test a C++ library with any Clang version, and not only the versions 
circumstantially provided by apt-get.

This action uses a number of alternatives to find or install Clang:

- The Clang path provided to 'path'
- Any other version of Clang it can find in the system
- Any other version of Clang available from APT
- A version of Clang from our own binary releases


==== Input Parameters

|===
|Parameter |Description |Default
|`version` |Version range or exact version of Clang to use, using SemVer's version range syntax. 

By default, it uses any version available in the environment.
. |`*`
|`path` |The clang or clang++ executable. We attempt to find Clang at this path first. |`clang++`
|`cache` |Used to specify whether the Clang installation should be cached in the case Clang needs to be downloaded."
. |`false`
|`architecture` |The target architecture (x86, x64). By default, this value is inferred.
. |
|`check-latest` |By default, when Clang is not available, this action will install the minimum version in the version spec.
This ensures the code respects its contract in terms of what minimum Clang version is supported.

Set this option if you want the action to check for the latest available version that satisfies the version spec
instead.
. |`false`
|`update-environment` |Set this option if you want the action to update environment variables. |`true`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

==== Outputs

|===
|Output |Description
|`cc` |The absolute path to the clang executable.
|`cxx` |The absolute path to the clang++ executable.
|`dir` |The absolute path to the Clang directory containing the executable.
|`version` |The installed Clang version. Useful when given a version range as input.
|`version-major` |The installed Clang version major. Useful when given a version range as input.
|`version-minor` |The installed Clang version minor. Useful when given a version range as input.
|`version-patch` |The installed Clang version patch. Useful when given a version range as input.
|`cache-hit` |A boolean value to indicate a cache entry was found
|===


== Contributions

If there's a platform where one of the actions does not work, feel free to submit a PR with adaptations and tests.

== License

[]
====
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
====

