= C++ Actions

This repository includes a number of useful GitHub actions to test C++ libraries.
Part of the difficulty to test C++ libraries comes from the diversity of the C++ ecosystem.
Our intention is to create a common and resilient set of actions that can work on as many environments as possible.

NOTE: READ THE DOCS: https://alandefreitas.github.io/cpp-actions/

== Actions
:reftext: Actions
:navtitle: All Actions

- <<package_install>>
- <<cmake_workflow>>
- <<boost_clone>>
- <<b2_workflow>>

=== Install dependencies [[package_install]]
:reftext: Install dependencies
:navtitle: Install dependencies Action

This action installs dependencies from multiple package managers for a workflow.

If vcpkg dependencies are required and vcpkg is not available, it will be installed.
Both vcpkg and its dependencies are cached.


==== Examples

Example 1:

[source,yml]
----
steps:
- name: Install packages
  uses: alandefreitas/cpp-actions/package_install
  id: package-install
  with:
    vcpkg: fmt
    apt-get: g++-11
    cxx: g++-11
    cc: gcc-11
----

Example 2 (`apt-get-ignore-missing`):

[source,yml]
----
steps:
- name: Install packages
  uses: alandefreitas/cpp-actions/package_install
  id: package-install
  with:
    vcpkg: fmt
    apt-get: g++-4.8 sudo software-properties-common tzdata wget curl apt-transport-https
      make apt-file unzip libssl-dev build-essential autotools-dev autoconf automake
      g++ libc++-helpers python ruby cpio gcc-multilib g++-multilib pkgconf python3
      ccache libpython-dev python3-distutils python3-pip git cmake
    apt-get-ignore-missing: 'true'
    cxx: g++-4.8
    cc: gcc-4.8
----

==== Input Parameters

|===
|Parameter |Description |Default
|`vcpkg` |List of packages we should install with vcpkg. (Whitespace-separated). |
|`apt-get` |List of packages we should install with apt-get. (Whitespace-separated). |
|`cxx` |C++ compiler used by vcpkg.

Setting the compiler is particularly important in Linux workflows that use `clang`, since `clang` might link 
`libc++` or `libstdc++`, while the default compiler used by vcpkg will usually be GCC linking `libstdc++`.

This would cause conflict in workflows that later attempt to use vcpkg dependencies.
. |
|`cc` |C compiler used by vcpkg. |
|`vcpkg_triplet` |The triplet used by vcpkg to install packages. |
|`vcpkg_dir` |The directory where vcpkg should be cloned and installed. |`vcpkg`
|`vcpkg_branch` |vcpkg branch we should use. |`master`
|`apt-get-retries` |Number of time we should retry when apt-get fails. |`1`
|`apt-get-sources` |List of sources for apt-get. |
|`apt-get-source-keys` |List of source keys for apt-get. |
|`apt-get-ignore-missing` |Whether apt-get should ignore missing packages. |`false`
|===

==== Outputs

|===
|Output |Description
|`vcpkg_toolchain` |vcpkg toolchain file
|`vcpkg_executable` |vcpkg toolchain file
|===
=== CMake Workflow [[cmake_workflow]]
:reftext: CMake Workflow
:navtitle: CMake Workflow Action

This action runs a complete CMake workflow from source files. A workflow is composed of the following steps:

- Configure
- Build
- Test
- Install

The action also sets up the environment for the workflow: 

- It validates the CMake version installed in the system, 
- Updates CMake if the library has a different minimum version, 
- Identifies what features the current CMake version supports, and 
- Runs a complete cmake workflow

The action will adjusts the parameters as needed according to the features that CMake version supports. 
For instance, 

- If the CMake version does not support the `-S ... -B ...` syntax, the action will create the build directory and
run the configuration step from there.
- If the specified or default generator is multi-config, `CMAKE_CONFIGURATION_TYPES` will be used instead of 
`CMAKE_BUILD_TYPE`, since the later is ignored by these generators.
- If the CMake version does not support the `cmake --install` syntax, the `cmake --build --target install`
will be use instead.
- If the CMake version does not support multiple targets in the `cmake --build` syntax, the action will run the build
step once for each target.

The action also creates GitHub annotations when warnings or errors are emitted at any of these steps. This includes
annotations for CMake errors at the configure step and build errors emitted from the compiler at the build step.


==== Examples

Example 1:

[source,yml]
----
steps:
- name: CMake Workflow
  uses: alandefreitas/cpp-actions/cmake_workflow
  with:
    source-dir: tests
    toolchain: ${{ steps.package-install.outputs.vcpkg_toolchain }}
    run-tests: 'true'
    install-prefix: $GITHUB_WORKSPACE/.local
    cxxstd: 17,20
    cxx: g++-11
    cc: gcc-11
    cmake-min-version: 3.15
    extra-args: -D BOOST_SRC_DIR=$GITHUB_WORKSPACE/boost-root
    ref-source-dir: .
----

Example 2 (`build-type`, `generator`):

[source,yml]
----
steps:
- name: CMake Workflow
  uses: alandefreitas/cpp-actions/cmake_workflow
  with:
    source-dir: tests
    generator: Unix Makefiles
    toolchain: ${{ steps.package-install.outputs.vcpkg_toolchain }}
    build-type: Debug
    run-tests: 'true'
    install-prefix: $GITHUB_WORKSPACE/.local
    cmake-min-version: 3.15
    extra-args: -D BOOST_SRC_DIR=$GITHUB_WORKSPACE/boost-root
    ref-source-dir: .
----

Example 3 (`cxxflags`):

[source,yml]
----
steps:
- name: CMake Workflow
  uses: alandefreitas/cpp-actions/cmake_workflow
  with:
    source-dir: tests
    toolchain: ${{ steps.package-install.outputs.vcpkg_toolchain }}
    run-tests: 'true'
    install-prefix: $GITHUB_WORKSPACE/.local
    cxxstd: 17,20
    cxx: clang++-12
    cxxflags: -stdlib=libc++
    cc: clang-12
    cmake-min-version: 3.15
    extra-args: -D BOOST_SRC_DIR=$GITHUB_WORKSPACE/boost-root
    ref-source-dir: .
----

==== Input Parameters

|===
|Parameter |Description |Default
|`source-dir` |Directory for the source files. |`.`
|`build-dir` |Directory for the binaries relative to the source directory. |`build`
|`cmake-min-version` |The minimum cmake version for this workflow. If the existing version is below that, the action attempts to update CMake. |`3.5`
|`cmake_exec` |The cmake executable. |`cmake`
|`cc` |Path to C compiler. |
|`cxx` |Path to C++ compiler. |
|`cxxstd` |List of standards with which cmake will build and test the program. |
|`cxxflags` |Force flags to be used with the C++ compiler. |
|`toolchain` |Path to toolchain. |
|`generator` |Generator name. |
|`build-type` |Build type. |`Release`
|`build-target` |Targets to build instead of the default target. |
|`install-prefix` |Path where the library should be installed. |`.local/usr`
|`run-tests` |Whether we should run tests. |`true`
|`install` |Whether we should install the library. 

The library is only installed once in the `install-prefix`.

The latest std version described in `cxxstd` is used for the installed version.
. |`true`
|`extra-args` |Extra arguments to cmake configure command. |
|`create-annotations` |Create github annotations on errors. |`true`
|`ref-source-dir` |A reference source directory for annotations. Any annotation filename will be relative to this directory. |`.`
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

=== Boost Clone [[boost_clone]]
:reftext: Boost Clone
:navtitle: Boost Clone Action

This action clones the Boost source directory, attempting to get it from the cache first. Only the specified
modules are cloned and cached. 

Besides the explicitly specified list of modules, the action can also scan directories for boost dependencies
to implicitly determine what modules should be cloned. 

The union of the implicitly and explicitly specified modules is cloned. Caching is based only on these dependencies.

For a project with about 5 boost dependencies, caching saves about 4 minutes in the workflow. When there's no
cache, the scanning scripting saves us about 3 minutes.


==== Example

[source,yml]
----
steps:
- name: Clone Boost.Variant2
  uses: alandefreitas/cpp-actions/boost_clone
  with:
    boost_dir: boost-root
    branch: master
    modules: variant2
----

==== Input Parameters

|===
|Parameter |Description |Default
|`boost_dir` |The boost directory. The default value assumes boost is in-source. |`boost`
|`branch` |Branch of the super-project. |`master`
|`patches` |Libraries used to patch the boost installation. |
|`modules` |The boost submodules we need to clone. |
|`scan-modules-dir` |An independent directory we should scan for boost dependencies to clone. |
|`scan-modules-ignore` |List of modules that should be ignored in scan-modules. |
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

=== B2 Workflow [[b2_workflow]]
:reftext: B2 Workflow
:navtitle: B2 Workflow Action

This action runs a complete B2 workflow from Boost source files.

It takes the Boost source directory and does whatever it needs to test the specified modules. This includes 
compiling `b2` if needed and generating a proper `user-config.jam` file.

This action is particularly useful for Boost library proposals.


==== Examples

Example 1:

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: gcc-11
    cxxstd: 17,20
----

Example 2 (`cxx`):

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: clang
    cxx: clang++-12
    cxxstd: 17,20
----

Example 3 (`address-model`):

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: msvc-14.3
    cxxstd: 17,20
    address-model: 32,64
----

Example 4 (`ubsan`):

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: gcc-11
    cxxstd: 17,20
    ubsan: 'true'
----

Example 5 (`cxxflags`, `linkflags`):

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: clang
    cxx: clang++-12
    cxxstd: 17,20
    cxxflags: -stdlib=libc++
    linkflags: -stdlib=libc++
----

Example 6 (`gcc_toolchain`):

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: clang
    cxx: clang++-8
    cxxstd: '17'
    gcc_toolchain: '7'
----

==== Input Parameters

|===
|Parameter |Description |Default
|`source-dir` |The boost source directory. |`.`
|`build-variant` |Custom build variants. |
|`modules` |The list of modules we should test. |
|`gcc_toolchain` |Create a special GCC toolchain for this version of GCC and update user-config.jam. |
|`toolset` |Toolset name. |
|`address-model` |Valid b2 list of address models. |
|`cxx` |Path to C++ compiler. |
|`cxxflags` |Extra compiler flags. |
|`linkflags` |Extra linker flags. |
|`cxxstd` |List of standards with which cmake will build and test the program. |
|`ubsan` |List of standards with which cmake will build and test the program. |`false`
|`threading` |b2 threading option. |
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===



== Contributions

If there's a platform where one of the actions does not work, feel free to submit a PR with adaptations and tests.

== License

[]
====
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
====

