= B2 Workflow [[b2_workflow]]
:reftext: B2 Workflow
:navtitle: Action: B2 Workflow

This action runs a complete B2 workflow from boost source files.

It takes the boost source directory and does whatever it needs to test the specified modules. This includes 
compiling `b2` if needed and generating a proper `user-config.jam` file.

This action is particularly useful for boost library proposals.


== Examples

Example 1:

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: gcc-11
    cxxstd: 17,20
----

Example 2 (`cxx`):

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: clang
    cxx: clang++-12
    cxxstd: 17,20
----

Example 3 (`address-model`):

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: msvc-14.3
    cxxstd: 17,20
    address-model: 32,64
----

Example 4 (`ubsan`):

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: gcc-11
    cxxstd: 17,20
    ubsan: 'true'
----

Example 5 (`cxxflags`, `linkflags`):

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: clang
    cxx: clang++-12
    cxxstd: 17,20
    cxxflags: -stdlib=libc++
    linkflags: -stdlib=libc++
----

Example 6 (`gcc_toolchain`):

[source,yml]
----
steps:
- name: Test Boost.Variant2
  uses: alandefreitas/cpp-actions/b2_workflow
  with:
    source-dir: boost-root
    modules: variant2
    toolset: clang
    cxx: clang++-8
    cxxstd: '17'
    gcc_toolchain: '7'
----

== Input Parameters

|===
|Parameter |Description |Default
|`source-dir` |The boost source directory. |`.`
|`build-variant` |Custom build variants. |(empty)
|`modules` |The list of modules we should test. |(empty)
|`gcc_toolchain` |Create a special GCC toolchain for this version of GCC and update user-config.jam. |(empty)
|`toolset` |Toolset name. |(empty)
|`address-model` |Valid b2 list of address models. |(empty)
|`cxx` |Path to C++ compiler. |(empty)
|`cxxflags` |Extra compiler flags. |(empty)
|`linkflags` |Extra linker flags. |(empty)
|`cxxstd` |List of standards with which cmake will build and test the program. |(empty)
|`ubsan` |List of standards with which cmake will build and test the program. |`false`
|`threading` |b2 threading option. |(empty)
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

