= Boost Clone [[boost_clone]]
:reftext: Boost Clone
:navtitle: Action: Boost Clone

This action clones the boost source directory, attempting to get it from the cache first. Only the specified
modules are cloned and cached. 

Besides specified an explicit list of modules, the action includes a script to scan dependencies before cloning 
boost and caching based only on these dependencies.

For a project with about 5 boost dependencies, caching saves about 4 minutes in the workflow. When there's no
cache, the scanning scripting saves us about 3 minutes.


== Example

[source,yml]
----
steps:
- name: Clone Boost.Variant2
  uses: alandefreitas/cpp-actions/boost_clone
  with:
    boost_dir: boost-root
    branch: master
    modules: variant2
----

== Input Parameters

|===
|Parameter |Description |Default
|`boost_dir` |The boost directory. The default value assumes boost is in-source. |`boost`
|`branch` |Branch of the super-project. |`master`
|`patches` |Libraries used to patch the boost installation. |(empty)
|`modules` |The boost submodules we need to clone. |(empty)
|`scan-modules-dir` |An independent directory we should scan for boost dependencies to clone. |(empty)
|`scan-modules-ignore` |List of modules that should be ignored in scan-modules. |(empty)
|`trace-commands` |Trace commands executed by the workflow. |`false`
|===

