== Install dependencies [[package_install]]

This actions installs dependencies from multiple package managers for a workflow.

If vcpkg dependencies are required and vcpkg is not available, it will be installed.
Both vcpkg and its dependencies can be cached.


=== Example

[source,yml]
----
      - name: Install packages
        uses: alandefreitas/cpp-actions/package_install
        id: package-install
        with:
          vcpkg: fmt
          apt-get: ${{ join(matrix.install, ' ') }} ${{ matrix.container && 'sudo software-properties-common tzdata wget curl apt-transport-https make apt-file unzip libssl-dev build-essential autotools-dev autoconf automake g++ libc++-helpers python ruby cpio gcc-multilib g++-multilib pkgconf python3 ccache libpython-dev python3-distutils python3-pip git cmake' }}
          apt-get-ignore-missing: ${{ matrix.container && 'true' }}
          cxx: ${{ matrix.cxx }} ${{ matrix.cxxflags }}
          cc: ${{ matrix.cc }}

----

=== Input Parameters

|===
|Parameter |Description |Default
|`vcpkg` |List of packages we should install with vcpkg. (Whitespace-separated). |(empty)
|`apt-get` |List of packages we should install with apt-get. (Whitespace-separated). |(empty)
|`cxx` |C++ compiler used by vcpkg.

Setting the compiler is particularly important in Linux workflows that use `clang`, since `clang` might link 
`libc++` or `libstdc++`, while the default compiler used by vcpkg will usually be GCC linking `libstdc++`.

This would cause conflict in workflows that later attempt to use vcpkg dependencies.
. |(empty)
|`cc` |C compiler used by vcpkg. |(empty)
|`vcpkg_triplet` |The triplet used by vcpkg to install packages. |(empty)
|`vcpkg_dir` |The directory where vcpkg should be cloned and installed. |`vcpkg`
|`vcpkg_branch` |vcpkg branch we should use. |`master`
|`apt-get-retries` |Number of time we should retry when apt-get fails. |`1`
|`apt-get-sources` |List of sources for apt-get. |(empty)
|`apt-get-source-keys` |List of source keys for apt-get. |(empty)
|`apt-get-ignore-missing` |Whether apt-get should ignore missing packages. |`false`
|===

=== Outputs

|===
|Output |Description
|`vcpkg_toolchain` |vcpkg toolchain file
|`vcpkg_executable` |vcpkg toolchain file
|===
