name: 'CMake Workflow'
description: |
  The cmake_workflow action is deprecated. Please use cmake-workflow instead.
  
  This action currently forwards all parameters to cmake-workflow and is included to
  allow users to upgrade their workflows.
  
  In a future release, this action will create a warning annotation and will later be removed.

inputs:
  source-dir:
    description: 'Directory for the source files.'
    required: false
    default: '.'
  cmake-exec:
    description: 'The cmake executable'
    required: false
    default: 'cmake'
  build-dir:
    description: 'Directory for the binaries relative to the source directory.'
    required: false
    default: 'build'
  cmake-min-version:
    description: 'The minimum cmake version for this workflow. If the existing version is below that, the action attempts to update CMake.'
    required: false
    default: '3.5'
  cc:
    description: 'Path to C compiler.'
    required: false
    default: ''
  cxx:
    description: 'Path to C++ compiler.'
    required: false
    default: ''
  cxxstd:
    description: 'List of standards with which cmake will build and test the program.'
    required: false
    default: ''
  cxxflags:
    description: 'Force flags to be used with the C++ compiler.'
    required: false
    default: ''
  toolchain:
    description: 'Path to toolchain.'
    required: false
    default: ''
  generator:
    description: 'Generator name.'
    required: false
    default: ''
  build-type:
    description: 'Build type.'
    required: false
    default: 'Release'
  build-target:
    description: 'Targets to build instead of the default target'
    required: false
    default: ''
  install-prefix:
    description: 'Path where the library should be installed.'
    required: false
    default: '.local/usr'
  run-tests:
    description: 'Whether we should run tests.'
    required: false
    default: 'true'
  install:
    description: |
      Whether we should install the library. 
      
      The library is only installed once in the `install-prefix`.
      
      The latest std version described in `cxxstd` is used for the installed version.
    required: false
    default: 'true'
  extra-args:
    description: 'Extra arguments to cmake configure command.'
    required: false
    default: ''
  create-annotations:
    description: 'Create github annotations on errors.'
    required: false
    default: 'true'
  ref-source-dir:
    description: 'A reference source directory for annotations. Any annotation filename will be relative to this directory.'
    required: false
    default: '.'
  trace-commands:
    description: 'Trace commands executed by the workflow.'
    required: false
    default: 'false'
  cpack-generators:
    description: 'Run cpack with the specified generators after the install step.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Run cmake workflow
      uses: ../cmake-workflow
      with:
        source-dir: ${{ inputs.source-dir }}
        build-dir: ${{ inputs.build-dir }}
        cmake-min-version: ${{ inputs.cmake-min-version }}
        cmake-exec: ${{ inputs.cmake-exec }}
        cc: ${{ inputs.cc }}
        cxx: ${{ inputs.cxx }}
        cxxstd: ${{ inputs.cxxstd }}
        cxxflags: ${{ inputs.cxxflags }}
        toolchain: ${{ inputs.toolchain }}
        generator: ${{ inputs.generator }}
        build-type: ${{ inputs.build-type }}
        build-target: ${{ inputs.build-target }}
        install-prefix: ${{ inputs.install-prefix }}
        run-tests: ${{ inputs.run-tests }}
        install: ${{ inputs.install }}
        extra-args: ${{ inputs.extra-args }}
        create-annotations: ${{ inputs.create-annotations }}
        ref-source-dir: ${{ inputs.ref-source-dir }}
        trace-commands: ${{ inputs.trace-commands }}
        cpack-generators: ${{ inputs.cpack-generators }}

