name: "Setup CMake"
description: |
  Set up a specific version of a CMake compiler and add it to the PATH.
  
  This action will also set-up any dependencies required by CMake.
  
  In most workflows, this is used as an auxiliary action for the xref:actions/cmake-workflow.adoc[] action,
  which already calls this action if necessary.


inputs:
  version:
    description: |
      Version range or exact version of CMake to use, using SemVer's version range syntax. 
      
      Reads from `cmake-file` input if unset.
      
      By default, it uses any version available in the environment.

    required: false
    default: '*'

  architecture:
    description: |
      The target architecture (x86, x64). By default, this value is inferred.
    required: false
    default: ''

  cmake-file:
    description: |
      File containing the CMake version to use in a cmake_minimum_required command. 
      
      Example: A CMakeLists.txt file containing a call to cmake_minimum_required."
    required: false
    default: 'CMakeLists.txt'

  path:
    description: 'The cmake executable. We attempt to find cmake at this path first.'
    required: false
    default: 'cmake'

  cmake-path:
    description: |
      The cmake executable. We attempt to find cmake at this path first. 
      This option is available for backwards compatibility and has priority over `path`.

    required: false
    default: ''

  cache:
    description: |
      Used to specify whether the CMake installation should be cached in the case CMake needs to be downloaded."
    required: false
    default: 'true'

  check-latest:
    description: |
      By default, when CMake is not available, this action will install the minimum version in the version spec.
      This ensures the code respects its contract in terms of what minimum CMake version is supported.
      
      Set this option if you want the action to check for the latest available version that satisfies the version spec
      instead.
    required: false
    default: 'false'

  update-environment:
    description: "Set this option if you want the action to update environment variables."
    required: false
    default: 'true'

  trace-commands:
    description: 'Trace commands executed by the workflow.'
    required: false
    default: 'false'

outputs:
  path:
    description: "The absolute path to the CMake executable."
  dir:
    description: "The absolute path to the CMake directory."
  version:
    description: "The installed CMake version. Useful when given a version range as input."
  version-major:
    description: "The installed CMake version major. Useful when given a version range as input."
  version-minor:
    description: "The installed CMake version minor. Useful when given a version range as input."
  version-patch:
    description: "The installed CMake version patch. Useful when given a version range as input."
  cache-hit:
    description: "A boolean value to indicate a cache entry was found"
  supports-path-to-build:
    description: "Whether CMake supports the -B <path-to-build> syntax"
  supports-parallel-build:
    description: "Whether CMake supports the -j <threads> syntax"
  supports-build-multiple-targets:
    description: "Whether CMake supports the --target with multiple targets"
  supports-cmake-install:
    description: "Whether CMake supports the cmake --install"

runs:
  using: 'node16'
  main: 'dist/index.js'
  post-if: success()
branding:
  icon: 'code'
  color: 'yellow'
