name: semver-utils
author: madhead <siarhei.krukau@gmail.com>
description: One-stop shop for working with semantic versions in your workflows
inputs:
  version:
    required: true
    description: A version to process
  compare-to:
    required: false
    description: A version to compare with, if any
  diff-with:
    required: false
    description: A version to diff with. If not specified, the version will be diffed with the `compare-to` input. If `compare-to` is not specified either, nothing happens.
  satisfies:
    required: false
    description: A range to check against
  identifier:
    required: false
    description: An identifier to pass to the semver's inc function
  lenient:
    required: false
    description: Do not fail on incorrect input
    default: 'true'
outputs:
  release:
    description: Version's release (major.minor.patch)
  major:
    description: Version's major number
  minor:
    description: Version's minor number
  patch:
    description: Version's patch number
  build:
    description: Version's build
  build-parts:
    description: Number of components in version's build. Individual сomponents are returned as `build-N` outputs, where an is an index from zero to `build-parts` - 1.
  prerelease:
    description: Version's pre-release
  prerelease-parts:
    description: Number of components in version's pre-release. Individual сomponents are returned as `prerelease-N` outputs, where an is an index from zero to `prerelease-parts` - 1.
  comparison-result:
    description: If the compare-to was provided, this output will contain "<" if comes after the version, ">" if it preceeds it, and "=" if they are equal
  diff-result:
    description: If the diff-to or compare-to were provided, this output will contain the diff result
  satisfies:
    description: true if the version satisfies the given range
  inc-major:
    description: A result of the call of the semver's `inc` function with `major` increment
  inc-premajor:
    description: A result of the call of the semver's `inc` function with `premajor` increment
  inc-minor:
    description: A result of the call of the semver's `inc` function with `minor` increment
  inc-preminor:
    description: A result of the call of the semver's `inc` function with `preminor` increment
  inc-patch:
    description: A result of the call of the semver's `inc` function with `patch` increment
  inc-prepatch:
    description: A result of the call of the semver's `inc` function with `prepatch` increment
  inc-prerelease:
    description: A result of the call of the semver's `inc` function with `prerelease` increment
  min-release:
    description: Min Version's release (major.minor.patch)
  min-major:
    description: Min Version's major number
  min-minor:
    description: Min Version's minor number
  min-patch:
    description: Min Version's patch number
  max-release:
    description: Max Version's release (major.minor.patch)
  max-major:
    description: Max Version's major number
  max-minor:
    description: Max Version's minor number
  max-patch:
    description: Max Version's patch number

runs:
  using: node16
  main: dist/index.js
branding:
  icon: hash
  color: gray-dark
