# npm install
# npx antora --fetch antora-playbook.yml
site:
  title: C++ Actions
  url: https://alandefreitas.github.io/cpp-actions/
  start_page: cpp-actions::index.adoc
  robots: allow
  keys:
    repo_url: 'https://github.com/alandefreitas/cpp-actions'

content:
  branches: [ master, develop ]
  tags: [ v* ]
  edit_url: 'https://github.com/alandefreitas/cpp-actions/edit/{refname}/{path}'
  sources:
    - url: https://github.com/alandefreitas/cpp-actions.git
      start_path: docs
      edit_url: 'https://github.com/alandefreitas/cpp-actions/edit/{refname}/{path}'

ui:
  bundle:
    url: ./ui/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

antora:
  extensions:
    - require: '@antora/lunr-extension' # https://gitlab.com/antora/antora-lunr-extension
      index_latest_only: true
    - '@antora/collector-extension'
    - require: '@sntke/antora-mermaid-extension'
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
      script_stem: header-scripts
      mermaid_initialize_options:
        start_on_load: true

asciidoc:
  extensions:
    - '@asciidoctor/tabs'
