# npm install
# npx antora --fetch local-antora-playbook.yml
site:
  title: C++ Actions
  url: https://alandefreitas.github.io/cpp-actions/
  start_page: cpp-actions::index.adoc
  robots: allow
content:
  edit_url: 'https://github.com/alandefreitas/cpp-actions/edit/{refname}/{path}'
  sources:
  - url: ..
    start_path: docs
    edit_url: 'https://github.com/alandefreitas/cpp-actions/edit/{refname}/{path}'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

