# npm install
# npx antora --fetch local-antora-playbook.yml
site:
  title: C++ Actions
  url: https://alandefreitas.github.io/cpp-actions/
  start_page: cpp-actions::index.adoc
  robots: allow
  keys:
    repo_url: 'https://github.com/alandefreitas/cpp-actions'
content:
  sources:
    - url: ..
      start_path: docs
      edit_url: 'https://github.com/alandefreitas/cpp-actions/edit/{refname}/{path}'
ui:
  bundle:
    url: https://github.com/bonitasoft/bonita-documentation-theme/releases/download/v1.11.0/bonita-documentation-theme-v1.11.0.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  extensions:
    - '@asciidoctor/tabs' # https://github.com/asciidoctor/asciidoctor-tabs

