name: Docs & Release

on:
  workflow_call:

jobs:
  docs:
    if: ${{ github.event_name == 'push' && (contains(fromJSON('["master", "develop"]'), github.ref_name) || startsWith(github.ref, 'refs/tags/')) }}
    defaults:
      run:
        shell: bash

    name: Publish
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    permissions:
      contents: write

    steps:
      - name: Clone cpp-actions
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Generate site
        working-directory: docs
        run: |
          npm install
          npx antora antora-playbook.yml

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/site

      - name: Changelog
        uses: ./create-changelog
        with:
          output-path: CHANGELOG.md
          thank-non-regular: ${{ startsWith(github.ref, 'refs/tags/') }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # if ref_name is develop, it only goes to the summary, so we explicitly link commits
          link-commits: ${{ github.ref_name == 'develop' }}
          trace-commands: true

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: LICENSE
          name: ${{ github.ref_name || github.ref }}
          tag_name: ${{ github.ref_name || github.ref }}
          body_path: CHANGELOG.md
          prerelease: false
          draft: false
          token: ${{ github.token }}
