name: CI

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - '*'
    tags:
      - "v*.*.*"

concurrency:
  group: ${{format('{0}:{1}', github.repository, github.ref)}}
  cancel-in-progress: true

jobs:
  dev-workflow:
    name: Developer Workflow
    uses: ./.github/workflows/ci-dev-workflow.yml
    secrets: inherit

  container-bootstrap:
    name: Container Bootstrap Tests
    needs: dev-workflow
    uses: ./.github/workflows/ci-container-bootstrap.yml
    secrets: inherit

  setup-program:
    name: Setup Program Tests
    needs: dev-workflow
    uses: ./.github/workflows/ci-setup-program.yml
    secrets: inherit

  create-changelog:
    name: Create Changelog Tests
    needs: dev-workflow
    uses: ./.github/workflows/ci-create-changelog.yml
    secrets: inherit

  cpp-matrix:
    name: Generate Test Matrix
    needs: dev-workflow
    uses: ./.github/workflows/ci-matrix.yml
    secrets: inherit

  build:
    name: Build & Test
    needs: cpp-matrix
    permissions:
      contents: write
    uses: ./.github/workflows/ci-build.yml
    with:
      matrix: ${{ needs.cpp-matrix.outputs.matrix }}
    secrets: inherit

  docs:
    name: Docs & Release
    needs: [build, container-bootstrap, setup-program, create-changelog]
    permissions:
      contents: write
    uses: ./.github/workflows/ci-docs.yml
    secrets: inherit
